### ISSUE TITLE
嘿嘿，尾行~小 Bug，-c 参数不指定默认无缓存

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mosdns-cn#1]
如题，设计就是默认没有缓存？

还有范例中：
`--remote-domain geosite.dat:geolocation-!cn`

这个后面不加引号在 bash 下运行会出错 `-bash: !cn: event not found`，应该为：
`--remote-domain 'geosite.dat:geolocation-!cn'`

**Comment by IrineSistiana** [comment]
是的。不指定就没缓存。

感谢纠正。
