### ISSUE TITLE
能不能优化一下日志

### ISSUE THREAD

**Issue by mobilefish** [IrineSistiana/mosdns-cn#10]
尝试开启--debug --log-file 后，用了一段时间，发现日志文件有点过于庞大，能否考虑优化一下日志大小，比如可以设置日志最高上限为2048Kb这样？

**Comment by IrineSistiana** [comment]
不建议平时使用开 --debug 和 --log-file，这些是调试的时候用的。

各个linux平台的守护进程都有记录日志和如何保管日志的功能。windows 的话建议用 winsw。
