### ISSUE TITLE
[Invaild]添加Bootstrap DNS支持

### ISSUE THREAD

**Issue by fzxiao233** [IrineSistiana/mosdns-cn#13]
当本机运行mosdns-cn (DOH)并且将DNS指向自己时，会发生鸡生蛋问题，无法查询到DoH域名的ip地址

**Comment by 70599** [comment]
https://github.com/IrineSistiana/mosdns-cn/blob/211de9701d0735e039e74749349f4c73453b7cfe/README.md?plain=1#L108

**Comment by IrineSistiana** [comment]
暂时没计划。如果是域名地址，可以用 `netaddr` 手动指定 ip。

目前貌似还没有哪个 DoH 的提供商换了自家 DNS 的 IP。所以动态解析跟手动指定静态区别不大。
