### ISSUE TITLE
请问为什么　--service 可以install done，但无法start？另外 geosite.dat:geolocation-!cn 必须用单引号，如果用双引号就提示 cn event not found。

### ISSUE THREAD

**Issue by jerrell851** [IrineSistiana/mosdns-cn#16]
# ./mosdns-cn --service install -s :5353 -c 512  --blacklist-domain "geosite.dat:category-ads-all" --local-upstream https://223.5.5.5/dns-query --local-domain "geosite.dat:cn" --local-ip "geoip-cn.dat:cn" --remote-upstream 127.0.0.0:7913 --remote-domain 'geosite.dat:geolocation-!cn'

2021-12-15T04:20:22.143Z	info	mosdns-cn/main.go:164	install: done

# ./mosdns-cn --service start
2021-12-15T04:20:30.861Z	fatal	mosdns-cn/main.go:162	start: "service" failed: exec: "service": executable file not found in $PATH

**Comment by IrineSistiana** [comment]
什么平台？

**Comment by jerrell851** [comment]
> 什么平台？

Openwrt+ARM64

**Comment by IrineSistiana** [comment]
openwrt 是 procd。不支持一键安装。
