### ISSUE TITLE
匹配顺序远程优先 bug?

### ISSUE THREAD

**Issue by swordsmile** [IrineSistiana/mosdns-cn#2]
运行命令如下 ：
./mosdns-cn -s :7053 -c 1024 --local-upstream 127.0.0.1 --local-domain 'geosite.dat:cn' --local-domain 'geosite.dat:apple-cn' --local-domain 'geosite.dat:google-cn' --local-ip 'geoip.dat:cn' --remote-upstream https://8.8.8.8/dns-query --remote-domain 'geosite.dat:geolocation-!cn' -v

结果如下：
debug   mosdns-cn/handler.go:90 [tools.l.google.com. IN A 38689 1] query is remote domain

geosite.dat:cn 和 geosite.dat:google-cn 里面都是包含域名 tools.l.google.com 的，为什么还会使用远程解析呢？难道远程优先？

**Comment by IrineSistiana** [comment]
是远程优先。因为远程优先的话，像 google.com 这种重点关怀域名永远不会出问题。虽然有些域名会绕路，但总能用。

**Comment by IrineSistiana** [comment]
想了想还是换成本地优先了。
