### ISSUE TITLE
请问会并发请求所有上游

### ISSUE THREAD

**Issue by fabaoin** [IrineSistiana/mosdns-cn#23]
远程上游服务器之间是用逗号分隔吧，那写了几个服务器，我看debug每个服务器都返回，那是以最快返回的IP地址为准吗？

**Comment by NagaseKouichi** [comment]
多个上游服务器是用逗号分隔？还是用多个--remote-upstream参数调用？比如

mosdns-cn -s :53 --local-upstream 223.5.5.5 --local-upstream 114.114.114.114 --remote-upstream 208.67.222.222:443 --remote-upstream tls://dns.google?netaddr=8.8.8.8:853 --remote-upstream https://dns.google/dns-query?netaddr=8.8.8.8 --remote-upstream tcp://176.103.130.130:5353 --local-ip geoip.dat:cn

**Comment by NagaseKouichi** [comment]
试了，用逗号分隔不行，会报错

**Comment by IrineSistiana** [comment]
> 远程上游服务器之间是用逗号分隔吧，那写了几个服务器，我看debug每个服务器都返回，那是以最快返回的IP地址为准吗？

并发请求所有服务器。取最快返回的应答。



> 多个上游服务器是用逗号分隔？还是用多个--remote-upstream参数调用？比如
> 
> mosdns-cn -s :53 --local-upstream 223.5.5.5 --local-upstream 114.114.114.114 --remote-upstream 208.67.222.222:443 --remote-upstream tls://dns.google?netaddr=8.8.8.8:853 --remote-upstream https://dns.google/dns-query?netaddr=8.8.8.8 --remote-upstream tcp://176.103.130.130:5353 --local-ip geoip.dat:cn

多个参数。
