### ISSUE TITLE
googleapis.cn被local_upstream抢答到北京电信

### ISSUE THREAD

**Issue by Moebyte** [IrineSistiana/mosdns-cn#25]
配置文件部分如下
local_ip: [geoip.dat:cn]
local_domain: [geosite.dat:cn]
remote_domain: [geosite.dat:geolocation-!cn,remotedomain.txt]

我把googleapis.cn写进了remotedomain.txt里面，但是在nslookup查询的时候，依旧被解析到北京电信，查看了log，是被本地电信dns解析了，nslookup services.googleapis.cn 1.1.1.1就是解析到美国谷歌云，导致google play下载的时候一直在pending
请问有什么办法能解决这个问题

**Comment by IrineSistiana** [comment]
Local 表的优先级高于 remote。这些域名在 geosite.dat:cn 内。要把他们从 local 表里去掉。
