### ISSUE TITLE
请问如何同时监听 ipv4与pv6的 port 53

### ISSUE THREAD

**Issue by delphinuz** [IrineSistiana/mosdns-cn#26]
server_addr 只能写一个，内容只能是 [::1]:53或是127.0.0.1:53，可以同时监听吗？谢谢。

**Comment by wkingnet** [comment]
你只写 :53

就同时监听v4和v6了

**Comment by IrineSistiana** [comment]
本地为什么还要同时监听？127.0.0.1:53 就行。

P.S. DNS 服务器不区分 IPv4 和 IPv6.
