### ISSUE TITLE
Openwrt 下 --service start 出错

### ISSUE THREAD

**Issue by hzqim** [IrineSistiana/mosdns-cn#27]
型号：FriendlyElec NanoPi R2S
架构 ： ARMv8 Processor rev 4
固件版本：OpenWrt 21.02.1

直接用预编译版本： mosdns-cn-linux-arm64.zip    v1.2.3

错误提示：
root@OpenWrt:~# mosdns-cn --service start
2022-05-23T14:10:49.574Z        fatal   mosdns-cn/main.go:198   start: "service" failed: exec: "service": executable file not found in $PATH

但是通过 /etc/init.d/mosdns-cn start 可以顺利启动 mosdns-cn

另外，请问如何在 Android 下进行？
谢谢！！！

**Comment by IrineSistiana** [comment]
openwrt 不支持 --service。

> 另外，请问如何在 Android 下进行？

不在本项目的讨论范围内。
