### ISSUE TITLE
能否支持屏蔽返回IPV6结果

### ISSUE THREAD

**Issue by Moebyte** [IrineSistiana/mosdns-cn#30]
mosdns里有这个功能，_prefer_ipv4/6: 自动判断域名是否是双栈域名然后屏蔽 IPv4/6 请求，不会影响纯 IPv6/4 域名。

**Comment by IrineSistiana** [comment]
这个功能算高级功能了，而且多数场景下需要按需灵活配置。放在 mosdns-cn 里不太合适。
